services:
  azure-sync:
    build: .
    container_name: azure-sync
    restart: unless-stopped
    ports:
      - "3420:3420"
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
      - /media/usbdrive/immich:/media/usbdrive/immich
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AZURE_CONNECTION_STRING=${AZURE_CONNECTION_STRING}
      - LOG_LEVEL=info
